name: arduino-build-workflow
'on': push
jobs:
  firmware_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load environment variables
        run: cat firmware/docker-build/build.env >> $GITHUB_ENV

      - name: Build docker image
        run: docker build firmware/docker-build -t "$IMAGE_NAME"

      - name: Run unit tests
        run: |
          cd firmware/tests
          ./run_tests.sh

      - name: Transpile html into header files
        run: ./firmware/transpile_html.sh

      - name: Build arduino firmware
        run: ./firmware/build.sh
